export const special = [
  {
    id: 1,
    name: "تیشرت مردانه اسپیور مدل 2m10-44 ",
    image: "/static/images/product1.jpg",
    category: "dress",
    price: "350000",
    withDiscount: "149000",
    currency: "تومان",
    gift: "14400",
    discountDate: "8/4/2021",
  },
  {
    id: 2,
    name: "گوشی موبایل اپل مدل iPhone 12 A2404 دو سیم‌ کارت ظرفیت 128 گیگابایت ",
    image: "/static/images/product2.jpg",
    category: "mobile",
    price: "25350000",
    withDiscount: "18550000",
    currency: "تومان",
    gift: "14400",
    discountDate: "8/4/2021",
  },
  {
    id: 3,
    name: "کوله پشتی کوهنوردی 75 لیتری فوروارد کد FCLT405",
    image: "/static/images/product3.jpg",
    category: "mobile",
    price: "979000",
    withDiscount: "369900",
    currency: "تومان",
    discountDate: "8/4/2021",
  },
  {
    id: 4,
    name: "کتاب دنیای سوفی اثر یوستین گوردر نشر ندای معاصر",
    image: "/static/images/product4.jpg",
    category: "mobile",
    price: "140000",
    withDiscount: "34600",
    currency: "تومان",
    gift: "8400",
    discountDate: "8/4/2021",
  },
  {
    id: 5,
    name: "کفش اسکیت برد کفش سعیدی مدل Sa 8000 ",
    image: "/static/images/product5.jpg",
    category: "mobile",
    price: "175000",
    withDiscount: "114000",
    currency: "تومان",
    discountDate: "8/4/2021",
  },
];

export const superMarket = [
  {
    id: 1,
    name: "چای سیاه سنتی انگلیسی توینینگز مقدار 450 گرم ",
    image: "/static/images/product6.jpg",
    category: "superMarket",
    price: "134900",
    withDiscount: "107500",
    currency: "تومان",
    gift: "5000",
    discountDate: "8/15/2021",
  },
  {
    id: 2,
    name: "میگو سایز 90-71 بیستون - 500 گرم",
    image: "/static/images/product7.jpg",
    category: "superMarket",
    price: "162000",
    withDiscount: "97200",
    currency: "تومان",
    gift: "3900",
    discountDate: "8/15/2021",
  },
  {
    id: 3,
    name: "اسپری چندمنظوره سطوح دامستوس مدل Purple حجم 750 میلی‌لیتر ",
    image: "/static/images/product8.jpg",
    category: "superMarket",
    price: "38000",
    withDiscount: "34200",
    currency: "تومان",
    gift: "1100",
    discountDate: "8/15/2021",
  },
  {
    id: 4,
    name: "مایع سفید کننده تاژ با رایحه لیمو مقدار 4000 گرم ",
    image: "/static/images/product9.jpg",
    category: "superMarket",
    price: "32500",
    withDiscount: "28500",
    currency: "تومان",
    gift: "1000",
    discountDate: "8/15/2021",
  },
  {
    id: 5,
    name: "پودر کیک وانیلی زر ماکارون مقدار 500 گرم ",
    image: "/static/images/product10.jpg",
    category: "superMarket",
    price: "21300",
    withDiscount: "16500",
    currency: "تومان",
    gift: "1000",
    discountDate: "8/15/2021",
  },
];

export const mobile = [
  {
    id: 1,
    name: "گوشی موبایل اپل مدل iPhone 12 A2404 دو سیم‌ کارت ظرفیت 128 گیگابایت ",
    image: "/static/images/product2.jpg",
    category: "mobile",
    price: "25350000",
    currency: "تومان",
  },
  {
    id: 2,
    name: " گوشی موبایل شیائومی مدل POCO M3 M2010J19CG دو سیم‌ کارت ظرفیت 128 گیگابایت ",
    image: "/static/images/product11.jpg",
    category: "mobile",
    price: "4175000",
    currency: "تومان",
  },
  {
    id: 3,
    name: "گوشی موبایل سامسونگ مدل Galaxy A32 SM-A325F/DS دو سیم‌کارت ظرفیت 128 گیگابایت و رم 6 گیگابایت",
    image: "/static/images/product12.jpg",
    category: "mobile",
    price: "6349000",
    currency: "تومان",
  },
  {
    id: 4,
    name: "گوشی موبایل اپل مدل iPhone 12 Pro Max A2412 دو سیم‌ کارت ظرفیت 256 گیگابایت ",
    image: "/static/images/product13.jpg",
    category: "mobile",
    price: "37500000",
    currency: "تومان",
  },
  {
    id: 5,
    name: "گوشی موبایل سامسونگ مدل Galaxy A12 SM-A125F/DS دو سیم کارت ظرفیت 64 گیگابایت ",
    image: "/static/images/product14.jpg",
    category: "mobile",
    price: "3920000",
    withDiscount: "3820000",
    currency: "تومان",
  },
  {
    id: 6,
    name: " گوشی موبایل شیائومی مدل POCO X3 Pro M2102J20SG دو سیم‌ کارت ظرفیت 128 گیگابایت و 6 گیگابایت رم",
    image: "/static/images/product15.jpg",
    category: "mobile",
    price: "6339000",
    currency: "تومان",
  },
];
